/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/heroModel.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/heroModel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tableLight.geometry} material={nodes.tableLight.material} position={[-1.751, 2.809, -0.406]} />
      <mesh geometry={nodes.chairU.geometry} material={nodes.chairU.material} position={[-0.383, 0.702, -0.704]} />
      <mesh geometry={nodes.chairD.geometry} material={nodes.chairD.material} />
      <mesh geometry={nodes.computer_screen.geometry} material={nodes.computer_screen.material} position={[-1.718, 1.536, -0.746]} />
      <mesh geometry={nodes.flash.geometry} material={nodes.flash.material} position={[-2.124, 1.123, 2.009]} />
      <mesh geometry={nodes.house.geometry} material={nodes.house.material} />
    </group>
  )
}

useGLTF.preload('/heroModel.glb')
