/*
 * @Descripttion: 
 * @version: 1.0
 * @Author: Hersynne
 * @Date: 2025-07-17 16:48:35
 * @LastEditors: Hersynne
 * @LastEditTime: 2025-07-18 19:06:20
 */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/myhouse.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useHelper, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { useControls } from 'leva';
import { RectAreaLightHelper } from 'three/examples/jsm/helpers/RectAreaLightHelper'

import { gsap } from 'gsap'

export function HeroModel(props) {
  const { nodes, materials } = useGLTF('/models/myhouse.glb')
  const texture = useTexture('/textures/house.png', (texture) => {
    texture.flipY = false
  })
  const board_texture = useTexture('/textures/board.png', (texture) => {
    // texture.flipY = false
  })
  const wheels_texture = useTexture('/textures/wheels.png', (texture) => {
    // texture.flipY = false
  })
  console.log(nodes)

  // 创建一个灯光引用  const rectLight = useRef();
  const rectLight = useRef();
  useHelper(rectLight, RectAreaLightHelper, "#fff");

  const { lightIns, lightColor, lightAngle, lightDistance } = useControls('light', {
    lightDistance: { value: 10, min: 0, max: 100, step: 1 },
    lightAngle: { value: -Math.PI / 10, min: -Math.PI, max: Math.PI, step: Math.PI / 365 },
    lightIns: { value: 80, min: 0, max: 200, step: 1 },
    lightColor: '#f5fff5'
  })
  useEffect(() => {
    if (!nodes.tableLight || !rectLight.current) return

    // 更新世界矩阵（确保 transform 正确）
    nodes.tableLight.updateWorldMatrix(true, false)

    const light = rectLight.current
    // 获取世界位置和旋转
    nodes.tableLight.getWorldPosition(light.position)
    nodes.tableLight.getWorldQuaternion(light.quaternion)
    light.rotation.x = -Math.PI / 2
    light.rotation.y = lightAngle
    // 你也可以选择设置方向朝某一点（例如 lookAt）
    // light.lookAt(0, 0, 0)

    light.width = 0.12
    light.height = 2.8

    // 设置其他参数
    light.intensity = lightIns
    light.color = new THREE.Color(lightColor)

  }, [nodes, lightIns, lightColor, lightAngle, lightDistance])


  const wheel1Ref = useRef()

  const handleClick = () => {
    console.log('')
    // 每次点击时，让轮子绕 Y 轴旋转两圈
    gsap.to(wheel1Ref.current.rotation, {
      x: wheel1Ref.current.rotation.x + Math.PI * 4, // 720°
      duration: 2,
      ease: 'power2.inOut',
    })
   
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.house.geometry} material={nodes.house.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      {/* CHAIR */}
      <mesh geometry={nodes.chairU.geometry} material={nodes.chairU.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      <mesh geometry={nodes.chairD.geometry} material={nodes.chairD.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      {/* TABLE */}
      <mesh geometry={nodes.table.geometry} material={nodes.table.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      {/* SKIDS */}
      <mesh geometry={nodes.skids1.geometry} material={nodes.skids1.material}>
        <meshStandardMaterial map={board_texture} />
      </mesh>
      <mesh geometry={nodes.skids2.geometry} material={nodes.skids2.material}>
        <meshStandardMaterial map={board_texture} />
      </mesh>
      <mesh geometry={nodes.skids3.geometry} material={nodes.skids3.material}>
        <meshStandardMaterial map={board_texture} />
      </mesh>
      <mesh geometry={nodes.skids4.geometry} material={nodes.skids4.material}>
        <meshStandardMaterial map={texture} />
      </mesh>

      {/* WHEELS */}
      {/* <group ref={wheel1Ref} onClick={handleClick}>
        <mesh geometry={nodes.wheel2.geometry} material={nodes.wheel2.material}>
          <meshStandardMaterial map={texture} />
        </mesh>
        <mesh geometry={nodes.wheel1.geometry} material={nodes.wheel1.material}>
          <meshStandardMaterial map={texture} />
        </mesh>
      </group>

      <mesh geometry={nodes.wheel3.geometry} material={nodes.wheel3.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      <mesh geometry={nodes.wheel4.geometry} material={nodes.wheel4.material}>
        <meshStandardMaterial map={texture} />
      </mesh>
      <mesh geometry={nodes.wheel11.geometry} material={nodes.wheel11.material}>
        <meshStandardMaterial map={wheels_texture} />
      </mesh>
      <mesh geometry={nodes.wheel22.geometry} material={nodes.wheel22.material}>
        <meshStandardMaterial map={wheels_texture} />
      </mesh>
      <mesh geometry={nodes.wheel33.geometry} material={nodes.wheel33.material}>
        <meshStandardMaterial map={wheels_texture} />
      </mesh>
      <mesh geometry={nodes.wheel44.geometry} material={nodes.wheel44.material}>
        <meshStandardMaterial map={wheels_texture} />
      </mesh> */}
      {/* <mesh geometry={nodes.tableLight.geometry} material={nodes.tableLight.material}>
        <meshBasicMaterial color="red" />
      </mesh> */}

      <rectAreaLight
        ref={rectLight}
        color={lightColor}
        intensity={lightIns}
        penumbra={1}
        castShadow
      />
    </group>
  )
}

useGLTF.preload('/models/myhouse.glb')
